import { PropsWithChildren } from 'react'
import { BaseLayout } from '../providers'
import { Footer } from '@/widgets/footer'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Naleystogram',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<BaseLayout>
			<main>{children}</main>
			<Footer />
		</BaseLayout>
	)
}
