import { AuthAbout } from '@/widgets/auth-about'
import { AuthLoginForm } from '@/features/auth-login'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Naleystogram - Авторизация',
	description: 'Generated by create next app'
}

export default function LoginPage() {
	return (
		<section className='container flex justify-between mb-24 mt-9 sm:mt-24 flex-wrap md:flex-nowrap'>
			<AuthAbout />
			<AuthLoginForm />
		</section>
	)
}
