import { PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import cn from 'classnames'
import { Providers } from './providers'
import { Inter } from 'next/font/google'
import './globals.css'

const interSans = Inter({
	variable: '--font-inter-sans',
	weight: ['400', '500', '600', '700', '800']
})

export const metadata: Metadata = {
	title: 'Naleystogram',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang='ru'>
			<body className={cn(interSans.variable)}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
