import { PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import cn from 'classnames'
import { Providers } from './providers'
import { Inter, Kanit } from 'next/font/google'
import './globals.css'
import { Footer } from '@/widgets/footer'

const inter = Inter({
	subsets: ['latin', 'cyrillic'],
	variable: '--font-inter',
	display: 'swap',
	weight: ['400', '500', '600', '700', '800']
})

const kanit = Kanit({
	subsets: ['latin'],
	variable: '--font-kanit',
	display: 'swap',
	weight: ['400', '500', '600', '700', '800']
})

export const metadata: Metadata = {
	title: 'Naleystogram',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang='ru'>
			<body className={cn(inter.variable, kanit.variable)}>
				<Providers>
					<main>{children}</main>
					<Footer />
				</Providers>
			</body>
		</html>
	)
}
