import { AuthAbout } from '@/widgets/auth-about'
import { AuthRegisterForm } from '@/features/auth-register'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Naleystogram - Регистрация',
	description: 'Generated by create next app'
}

export default function RegisterPage() {
	return (
		<section className='container flex justify-between mb-24 mt-9 sm:mt-24 flex-wrap md:flex-nowrap'>
			<AuthAbout />
			<AuthRegisterForm />
		</section>
	)
}
