import { PropsWithChildren } from 'react'
import { BaseLayout } from '../providers'
import { Footer } from '@/widgets/footer'
import { Metadata } from 'next'
import { Header } from '@/widgets/header'

export const metadata: Metadata = {
	title: 'Naleystogram',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<BaseLayout>
			<Header />
			<main className='container mt-4'>{children}</main>
			<Footer />
		</BaseLayout>
	)
}
